### Probar la ruta GET "/"
GET http://localhost:5000/

### Probar la ruta POST "/users" (crear usuario)
POST http://localhost:5000/users
Content-Type: application/json

{
  "name": "Nuevo Usuario",
  "last_name": "Apellido Nuñez",
  "numbers": 35,
  "addres": "Calle Falsa 123"
}

### Probar la ruta GET "/users/<user_id>" (obtener usuario por ID)
GET http://localhost:5000/users/1